#!/bin/bash

. config

if [ -e $SVNDIR ]
then
   echo "A SVN dir is in place. Please svntoprod first."
   exit
fi

if [ $1 ] 
then
	if [ $BRANCH ]
	then
   		svn update -R $BRANCH ${BASEDIR}/${1}
   	else
   		svn update ${BASEDIR}/${1}
   	fi
else
	if [ $BRANCH ]
	then
   		svn update -R $BRANCH ${BASEDIR}
   	else
   		svn update ${BASEDIR}
   	fi
fi

chown -R ${FILESERVUSER}:${FILESERVGROUP} $BASEDIR
chmod -R g+w $BASEDIR
chmod -R ugo+r $BASEDIR
